import type { Report } from "@/types/report.ts"

export const MOCK_REPORTS: Report[] = [
  {
    id: "1",
    title: "Buraco na Avenida Amazonas",
    description: "Buraco grande na pista, proximo ao semaforo. Risco de acidentes para veiculos e pedestres.",
    category: "infraestrutura",
    latitude: -19.9191,
    longitude: -43.9386,
    likes: 12,
    createdAt: "2026-02-15T10:30:00Z",
  },
  {
    id: "2",
    title: "Poste sem iluminacao na Rua Curitiba",
    description: "Poste apagado ha mais de 15 dias. Rua completamente escura a noite.",
    category: "iluminacao",
    latitude: -19.9225,
    longitude: -43.9352,
    likes: 8,
    createdAt: "2026-02-18T14:15:00Z",
  },
  {
    id: "3",
    title: "Lixo acumulado na Praca da Liberdade",
    description: "Grande acumulo de lixo proximo aos bancos. Lixeiras transbordando.",
    category: "lixo",
    latitude: -19.9320,
    longitude: -43.9380,
    likes: 23,
    createdAt: "2026-02-20T08:00:00Z",
  },
  {
    id: "4",
    title: "Alagamento na Av. Tereza Cristina",
    description: "Alagamento constante em dias de chuva. Bueiro entupido impede o escoamento.",
    category: "alagamento",
    latitude: -19.9450,
    longitude: -43.9560,
    likes: 45,
    createdAt: "2026-02-22T16:45:00Z",
  },
  {
    id: "5",
    title: "Semaforo quebrado no cruzamento",
    description: "Semaforo intermitente na esquina da Rua dos Goitacazes com Av. Augusto de Lima.",
    category: "transito",
    latitude: -19.9180,
    longitude: -43.9410,
    likes: 17,
    createdAt: "2026-02-24T09:20:00Z",
  },
  {
    id: "6",
    title: "Area insegura proximo ao viaduto",
    description: "Relatos frequentes de assaltos na regiao do viaduto Santa Tereza durante a noite.",
    category: "seguranca",
    latitude: -19.9250,
    longitude: -43.9300,
    likes: 31,
    createdAt: "2026-02-25T11:10:00Z",
  },
]
